### ISSUE TITLE
Missing officer system file

### ISSUE THREAD

**Issue by npelikan** [ardata-fr/mschart#2]
Hi,

When I install `officer` and `mschart` and attempt to create a test chart using `iris` data, I receive the following error message: 
```
> testdoc <- ph_with_chart(testdoc, value = bar_test)
Error: '' does not exist in current working directory
```

traceback() on this error suggests a missing system file from the `officer` package:
```
> traceback()
9: stop("'", path, "' does not exist", if (!is_absolute_path(path)) paste0(" in current working directory ('", 
       getwd(), "')"), ".", call. = FALSE)
8: check_path(path)
7: path_to_connection(x)
6: read_xml.character(system.file(package = "officer", "template", 
       "chart.xml"))
5: read_xml(system.file(package = "officer", "template", "chart.xml"))
4: format.ms_chart(value, id_x = id_x, id_y = id_y)
3: format(value, id_x = id_x, id_y = id_y)
2: pml_chart(x, value, id_x = "64451712", id_y = "64453248")
1: ph_with_chart(testdoc, value = bar_test)
```

**Comment by davidgohel** [comment]
Hi

Could you update with the new version? It should be fixed now. Could you add your sessionInfo() result also?

**Comment by npelikan** [comment]
Hi David,

Still the same error, slightly different traceback this time:
```
> traceback()
9: stop("'", path, "' does not exist", if (!is_absolute_path(path)) paste0(" in current working directory ('", 
       getwd(), "')"), ".", call. = FALSE)
8: check_path(path)
7: path_to_connection(x)
6: read_xml.character(system.file(package = "mschart", "template", 
       "chart.xml"))
5: read_xml(system.file(package = "mschart", "template", "chart.xml"))
4: format.ms_chart(value, id_x = id_x, id_y = id_y)
3: format(value, id_x = id_x, id_y = id_y)
2: pml_chart(x, value, id_x = "64451712", id_y = "64453248")
1: ph_with_chart(testdoc, value = linec)
```

```> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] mschart_0.1.0 officer_0.1.5

loaded via a namespace (and not attached):
 [1] zip_1.0.0          Rcpp_0.12.12       compiler_3.4.0    
 [4] cellranger_1.1.0   git2r_0.19.0       plyr_1.8.4        
 [7] bindr_0.1          R.methodsS3_1.7.1  R.utils_2.5.0     
[10] base64enc_0.1-3    tools_3.4.0        digest_0.6.12     
[13] uuid_0.1-2         memoise_1.1.0      tibble_1.3.3      
[16] gtable_0.2.0       pkgconfig_2.0.1    rlang_0.1.1       
[19] openxlsx_4.0.17    curl_2.8.1         bindrcpp_0.2      
[22] httr_1.2.1         withr_2.0.0        dplyr_0.7.2       
[25] xml2_1.1.1         gdtools_0.1.4      devtools_1.13.2   
[28] grid_3.4.0         glue_1.1.1         data.table_1.10.4 
[31] R6_2.2.2           ggplot2_2.2.1.9000 purrr_0.2.3       
[34] magrittr_1.5       scales_0.4.1.9002  htmltools_0.3.6   
[37] assertthat_0.2.0   colorspace_1.3-2   lazyeval_0.2.0    
[40] munsell_0.4.3      R.oo_1.21.0  
```

**Comment by davidgohel** [comment]
I don't know what code you ran. With the following one I get no error:

    library(mschart)
    library(magrittr)
    library(officer)
    
    my_barchart_01 <- ms_barchart(data = browser_data, x = "browser",
                                  y = "value", group = "serie")
    
    doc <- read_pptx() %>%
      add_slide(layout = "Title and Content", master = "Office Theme")
    doc <- ph_with_chart(doc, value = my_barchart_01)
    
    target_ <- tempfile(fileext = ".pptx")
    print(doc, target = target_) %>% browseURL()

**Comment by npelikan** [comment]
Hi @davidgohel 

Running the exact code you posted on a new R instance returns the same error I pasted above.

**Comment by ksedr** [comment]
Hi David,
I got the same error as Nick.
There is no `system.file(package = "mschart", "template", "chart.xml")` in the repository.

**Comment by davidgohel** [comment]
OK, don't know exactly why this xml did not go in GH but now it is ok

**Comment by npelikan** [comment]
that fix worked, thanks
